spring:
  datasource:
    url: ${urlConexionBd}
    username: ${userBd}
    password: ${passwordBd}

edi:
  seguridad:
    jwt:
      secret-key: ${jwtSecretKey}
      issuer: ${EDI_JWT_ISSUER:msedi-autenticacion}
      audience: ${EDI_JWT_AUDIENCE:edi}
