server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /msedi-catalogos
  forward-headers-strategy: framework

spring:
  profiles:
    default: local
  application:
    name: msedi-catalogos
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      read-only: true
      initialization-fail-timeout: ${DB_INITIALIZATION_FAIL_TIMEOUT:1}
      connection-init-sql: SET TIME ZONE '${EDI_TIME_ZONE:America/Mexico_City}'
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: non_null
    time-zone: ${EDI_TIME_ZONE:America/Mexico_City}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

edi:
  time-zone: ${EDI_TIME_ZONE:America/Mexico_City}
